first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
middle_name = input("Enter your middle name: ")
age = int(input("Enter your age: "))
school = input("Enter your school name: ")
grade = int(input("Enter your grade: "))
hours_per_day = int(input("Enter your hours per day: "))
print('-' * 99)
print('First name:', first_name, type(first_name))
print('Last name: ', last_name, type(last_name))
print('Middle_name: ', middle_name, type(middle_name))
print('Age: ', age, type(age))
print('School: ', school, type(school))
print('Grade: ', grade, type(grade))
print('Age: ', age, type(age))
print('Grade: ', grade, type(grade))
print('Hours per day: ', hours_per_day, type(hours_per_day))
full_name = f'{first_name} {middle_name} {last_name}'
print(full_name)
print(f'Hours per 5 days:  {hours_per_day * 5}')
print(f'Hours per 10 days:  {hours_per_day * 10}')